# -*- coding: utf-8 -*-
"""Copy of Assigment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUYaXLeQ2mEVUS1W5lWlDGG6XkE4ntQx
"""

# 👇 Force install langchain-core before importing anything
import subprocess
import sys

required_packages = [
    "langchain-core==0.1.33",
    "langchain==0.1.14",
    "langchain-community==0.0.19",
    "langchain-google-genai==0.0.8",
    "langchain-tavily==0.0.7",
    "google-generativeai==0.3.2",
]

for package in required_packages:
    subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", package])

# ✅ Now imports will work
import streamlit as st
import os
import requests
from typing import Dict, Any
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_tavily import TavilySearch
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate

st.set_page_config(page_title="Travel Assistant", page_icon="🌍")

st.title("🌍 AI Travel Assistant")

# 🔑 API Key Inputs
google_api_key = st.text_input("🔐 Enter your Google API Key", type="password")
tavily_api_key = st.text_input("🔐 Enter your Tavily API Key", type="password")
weather_api_key = st.text_input("🔐 Enter your Weather API Key", type="password")

# 🌍 Destination Input
destination = st.text_input("📍 Where are you planning to go?")

# When user clicks the button
if st.button("Get Travel Info") and all([google_api_key, tavily_api_key, weather_api_key, destination]):
    # Set environment variables
    os.environ["GOOGLE_API_KEY"] = google_api_key
    os.environ["TAVILY_API_KEY"] = tavily_api_key
    WEATHER_API_KEY = weather_api_key

    # 🌤️ Custom weather tool
    @tool
    def get_weather(location: str) -> Dict[str, Any]:
        """
        Get current weather for a location.
        """
        try:
            url = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={WEATHER_API_KEY}&units=metric"
            response = requests.get(url)
            data = response.json()

            if data.get("cod") != 200:
                return {"error": data.get("message", "Location not found")}

            weather = {
                "location": location,
                "temperature": data["main"]["temp"],
                "description": data["weather"][0]["description"],
                "humidity": data["main"]["humidity"],
                "wind_speed": data["wind"]["speed"]
            }
            return weather

        except Exception as e:
            return {"error": str(e)}

    # 🔍 Tavily search tool
    search_tool = TavilySearch(max_results=3)

    # 🤖 Gemini LLM
    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0)

    # Tools and prompt
    tools = [get_weather, search_tool]
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful travel assistant."),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}")
    ])

    # Agent setup
    agent = create_tool_calling_agent(
        llm=llm,
        tools=tools,
        prompt=prompt
    )
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

    with st.spinner("Thinking... 🤔"):
        response = agent_executor.invoke({"input": f"Tell me the current weather and top attractions in {destination}."})
        st.subheader("✈️ Travel Assistant Result")
        st.write(response["output"])

elif st.button("Get Travel Info"):
    st.warning("Please fill in all API keys and destination.")
